#!/bin/bash
echo "========================================="
echo "  汽车分期管理平台 - 手机端"
echo "========================================="
echo ""
echo "请选择部署方式："
echo "1. Cloudflare Pages (免费，推荐)"
echo "2. Vercel (免费，推荐）"
echo "3. 阿里云OSS (便宜，约0.12元/月）"
echo ""
echo "详细步骤请参考 DEPLOY.md"
echo ""
echo "快速部署到 GitHub + Cloudflare Pages："
echo "1. 把本文件夹内容上传到 GitHub 仓库"
echo "2. 访问 https://pages.cloudflare.com"
echo "3. Connect GitHub → 选择仓库 → Deploy"
echo ""
echo "部署完成后修改 js/api.js 里的 API_BASE 为你的公网地址"
